from time import sleep
from env import *
import spotipy
from spotipy.oauth2 import SpotifyOAuth

CLIENT_REDIRECT_URI = "https://example.com"
SONG_SEARCH_LIMIT = 5
SPOTIFY_MARKET = "IT"

def create_spotify_playlist(songs : list, country: str, moth : str, year : str):
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=CLIENT_ID_SPOTIFY,
                                                   client_secret=CLIENT_SECRET_SPOTIFY,
                                                   redirect_uri=CLIENT_REDIRECT_URI,
                                                   scope="playlist-modify-private",
                                                   show_dialog=True))

    # get user id
    user_id = sp.current_user()["id"]

    # get songs uri
    uris = []

    for song in songs:

        query = f"track: {song}"
        json = sp.search(q=query, limit=SONG_SEARCH_LIMIT, type="track", market=SPOTIFY_MARKET)

        items = json["tracks"]["items"]

        added = False
        for i in range(len(items)):

            if items[i]["name"] == song:
                track_uri = items[i]["uri"]
                uris.append(track_uri)
                added = True
                break

        if not added:
            print(f"❌ Not added {song}: song title mismatch")
        else:
            print(f"✅ Added {song}!")

        sleep(0.1)

    print(f"\n\nFound {len(uris)}/{len(songs)} songs")

    # create the playlist and add songs
    playlist_name = f"Gemini generated Billboard {len(songs)}: from {country} in {moth} {year}"
    json = sp.user_playlist_create(user=user_id, name=playlist_name, public=False,
                                   description=f"This is a playlist generated by gemini AI")
    sp.playlist_add_items(playlist_id=json["id"], items=uris)